### ISSUE TITLE
Load error: unresolve external:runtime.writeBarrier

### ISSUE THREAD

**Issue by introspection3** [pkujhd/goloader#71] opened 2023-03-10 09:09 UTC
1.20.1 windows 10

package pkg

type Farmer struct {
	Name *string
}

func (f *Farmer) Say(word string) {
	f.Name = &word
}
func (f *Farmer) Get() string {
	return *f.Name
}
func New() any {
	return &Farmer{}
}

////////////
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
	"unsafe"

	"github.com/pkujhd/goloader"
)

type arrayFlags struct {
	File    []string
	PkgPath []string
}

func (i *arrayFlags) String() string {
	return "my string representation"
}

func (i *arrayFlags) Set(value string) error {
	s := strings.Split(value, ":")
	i.File = append(i.File, s[0])
	var path string
	if len(s) > 1 {
		path = s[1]
	}
	i.PkgPath = append(i.PkgPath, path)
	return nil
}

type IPerson interface {
	Say(word string)
	Get() string
}

func parse(file, pkgpath *string) {
	if *file == "" {
		flag.PrintDefaults()
		return
	}
	f, err := os.Open(*file)
	if err != nil {
		fmt.Printf("%# v\n", err)
		return
	}
	obj, err := goloader.Parse(f, pkgpath)
	fmt.Printf("%# v\n", obj)
	f.Close()
	if err != nil {
		fmt.Printf("error reading %s: %v\n", *file, err)
		return
	}
}
func main() {

	symPtr := make(map[string]uintptr)
	err := goloader.RegSymbol(symPtr)
	if err != nil {
		fmt.Println(err)
		return
	}

	// most of time you don't need to register function, but if loader complain about it, you have to.

	str := make([]string, 0)

	goloader.RegTypes(symPtr, fmt.Sprint, str)

	//var file string = "./f.o"
	//var pkg string = "stduy1/pkg"
	//parse(&file, &pkg)
	linker, err := goloader.ReadObjs([]string{"./f.o"}, []string{"stduy1/pkg"})
	if err != nil {
		fmt.Println(err)
		return
	}

	var mmapByte []byte

	codeModule, err := goloader.Load(linker, symPtr)
	if err != nil {
		fmt.Println("Load error:", err)
		return
	}
	runFuncPtr := codeModule.Syms["pkg.New"]
	if runFuncPtr == 0 {
		fmt.Println("Load error! not find function:", "pkg.New")
		return
	}
	funcPtrContainer := (uintptr)(unsafe.Pointer(&runFuncPtr))
	runFunc := *(*func() any)(unsafe.Pointer(&funcPtrContainer))
	obj := runFunc().(IPerson)
	obj.Say("hello")

	codeModule.Unload()

	// a strict test, try to make mmap random
	if mmapByte == nil {
		mmapByte, err = goloader.Mmap(1024)
		if err != nil {
			fmt.Println(err)
		}
		b := make([]byte, 1024)
		copy(mmapByte, b) // reset all bytes
	} else {
		goloader.Munmap(mmapByte)
		mmapByte = nil
	}

}
![image](https://user-images.githubusercontent.com/12368358/224273739-e7c4eb20-a1aa-4d8e-8c9d-5785abd84246.png)

**Comment by pkujhd** [comment] 2023-03-10 10:26
@introspection3  
无法复现你的错误，你给出的例子执行结果应该是

panic: interface conversion: *pkg.Farmer is not main.IPerson: missing method Get

goroutine 1 [running]:
main.main()
        D:/Code/go/goloader/loader.go:95 +0x39c

这个问题目前未处理，你可以参考https://github.com/eh-steve/goloader/tree/jit

**Comment by pkujhd** [comment] 2023-03-10 10:54
Duplicate of #32

**Closed** 2023-03-10 10:54 UTC
Labels: question

**Comment by introspection3** [comment] 2023-03-10 10:56
PS F:\goprjs\s3> go get  "github.com/eh-steve/goloader/jit"
go: github.com/eh-steve/goloader@v0.0.0-20221026112716-fed0a9e75321: parsing go.mod:
        module declares its path as: github.com/pkujhd/goloader
                but was required as: github.com/eh-steve/goloader

**Comment by introspection3** [comment] 2023-03-12 06:56
goloader jit project has something wrong

**Comment by eh-steve** [comment] 2023-04-05 20:06
This should be fixed since https://github.com/eh-steve/goloader/commit/06a14a6e49922f03bbfeaed5a701a1a9e4dc6d27, the latest version should be go gettable now

**Comment by introspection3** [comment] 2023-04-12 00:56
@eh-steve Can we use go get -u github.com/pkujhd/goloader to resovle this bug
